# Generated by Django 5.0.7 on 2024-07-21 01:26

import meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='access_code',
            field=models.CharField(default=meetings.models.generate_access_code, max_length=32, unique=True),
        ),
    ]
